name = "HPHawkes"
uuid = "3da29ac6-ae4f-483c-8304-61a24d15370b"
authors = ["Seyoon Ko <kos@ucla.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
